# Generated by Django 5.1.1 on 2024-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_jobseekerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(default='Изображение отсутствует', upload_to='work/static/users/img'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/users/resumes'),
        ),
    ]
