# Generated by Django 5.1.1 on 2024-10-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_employerprofile_updated_at_and_more'),
        ('work', '0003_remove_jobcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers', to='work.profession'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(choices=[('none', 'Без образования'), ('school', 'Школьное образование'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Аспирант'), ('doctorate', 'Доктор наук')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('job_seeker', 'Job Seeker'), ('moderation', 'Moderation')], default='job_seeker', max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='ФИО'),
        ),
    ]
