# Generated by Django 5.1.1 on 2024-11-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employerprofile_user_and_more'),
        ('work', '0004_alter_jobcategory_name_alter_profession_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers', to='work.profession'),
        ),
    ]
