# Generated by Django 5.1.1 on 2024-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_jobseekerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/static/users/img/vindicta.jpg', null=True, upload_to='users/static/users/img', verbose_name='Аватар'),
        ),
    ]
