# Generated by Django 5.1.1 on 2024-10-10 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_employerprofile_updated_at_and_more'),
        ('work', '0002_alter_job_category_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Профессия', to='work.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Vacansy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('responsobilities', models.TextField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('experience_required', models.IntegerField(blank=True, null=True, verbose_name='Требуемый опыт работы')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессия')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус вакансии')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('job_type', models.CharField(choices=[('full_time', 'Полный рабочий день'), ('part_time', 'Неполный рабочий день'), ('contract', 'Контракт'), ('internship', 'Стажировка')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work.jobcategory', verbose_name='Категория профессии')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile', verbose_name='Работодатель')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
