# Generated by Django 5.1.1 on 2024-11-01 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employerprofile_user_and_more'),
        ('work', '0003_remove_jobcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории профессий'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='work.jobcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название профессии'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('experience_required', models.IntegerField(blank=True, null=True, verbose_name='Требуемый опыт работы (в годах)')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус вакансии')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('job_type', models.CharField(choices=[('full_time', 'Полный рабочий день'), ('part_time', 'Неполный рабочий день'), ('contract', 'Контракт'), ('internship', 'Стажировка')], max_length=20, verbose_name='Тип занятости')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work.jobcategory', verbose_name='Категория профессии')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile', verbose_name='Работодатель')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='work.profession', verbose_name='Профессия')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacansy',
        ),
    ]
