# Generated by Django 5.1.1 on 2024-11-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('reviewed', 'Рассмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус отклика'),
        ),
    ]
